# Trexquant Interview Project (The Hangman Game)

* Copyright Trexquant Investment LP. All Rights Reserved. 
* Redistribution of this question without written consent from Trexquant is prohibited

## Instruction:
For this coding test, your mission is to write an algorithm that plays the game of Hangman through our API server. 

When a user plays Hangman, the server first selects a secret word at random from a list. The server then returns a row of underscores (space separated)—one for each letter in the secret word—and asks the user to guess a letter. If the user guesses a letter that is in the word, the word is redisplayed with all instances of that letter shown in the correct positions, along with any letters correctly guessed on previous turns. If the letter does not appear in the word, the user is charged with an incorrect guess. The user keeps guessing letters until either (1) the user has correctly guessed all the letters in the word
or (2) the user has made six incorrect guesses.

You are required to write a "guess" function that takes current word (with underscores) as input and returns a guess letter. You will use the API codes below to play 1,000 Hangman games. You have the opportunity to practice before you want to start recording your game results.

Your algorithm is permitted to use a training set of approximately 250,000 dictionary words. Your algorithm will be tested on an entirely disjoint set of 250,000 dictionary words. Please note that this means the words that you will ultimately be tested on do NOT appear in the dictionary that you are given. You are not permitted to use any dictionary other than the training dictionary we provided. This requirement will be strictly enforced by code review.

You are provided with a basic, working algorithm. This algorithm will match the provided masked string (e.g. a _ _ l e) to all possible words in the dictionary, tabulate the frequency of letters appearing in these possible words, and then guess the letter with the highest frequency of appearence that has not already been guessed. If there are no remaining words that match then it will default back to the character frequency distribution of the entire dictionary.

This benchmark strategy is successful approximately 18% of the time. Your task is to design an algorithm that significantly outperforms this benchmark.

In [1]:
import json
import requests
import random
import string
import secrets
import time
import re
import collections

try:
    from urllib.parse import parse_qs, urlencode, urlparse
except ImportError:
    from urlparse import parse_qs, urlparse
    from urllib import urlencode

from requests.packages.urllib3.exceptions import InsecureRequestWarning

requests.packages.urllib3.disable_warnings(InsecureRequestWarning)

In [2]:
class HangmanAPI(object):
    def __init__(self, access_token=None, session=None, timeout=None):
        self.hangman_url = self.determine_hangman_url()
        self.access_token = access_token
        self.session = session or requests.Session()
        self.timeout = timeout
        self.guessed_letters = []
        
        full_dictionary_location = "words_250000_train.txt"
        self.full_dictionary = self.build_dictionary(full_dictionary_location)        
        self.full_dictionary_common_letter_sorted = collections.Counter("".join(self.full_dictionary)).most_common()
        
        self.current_dictionary = []
        
    @staticmethod
    def determine_hangman_url():
        links = ['https://trexsim.com', 'https://sg.trexsim.com']

        data = {link: 0 for link in links}

        for link in links:

            requests.get(link)

            for i in range(10):
                s = time.time()
                requests.get(link)
                data[link] = time.time() - s

        link = sorted(data.items(), key=lambda x: x[1])[0][0]
        link += '/trexsim/hangman'
        return link
    import collections
    import re

# class GuessingGame:
#     def __init__(self):
#         # Initialize an empty list for the current dictionary of words
#         self.current_dictionary = []
#         # Initialize an empty set to keep track of guessed letters
#         self.guessed_letters = set()

#     def load_dictionary(self, words):
#         # Load the dictionary of words into the current_dictionary list
#         self.current_dictionary = words

    def guess(self, word): # word input example: "_ p p _ e "
        ###############################################
        # Replace with your own "guess" function here #
        ###############################################

        # clean the word so that we strip away the space characters
        # replace "_" with "." as "." indicates any character in regular expressions
        clean_word = word[::2].replace("_",".")
        
        def contains_non_dot_characters(input_string):
            for char in input_string:
                if char != '.':
                    return True
            return False
        
        bigram_candidates = extract_characters_with_underscore(word)
                   #removed print

        # print('bigram_candidates: ', bigram_candidates)
        if len(bigram_candidates)>0:
            terminal_char_only = False
        else:
                       #removed print

            # print('Setting terminal_char_only to True')
            terminal_char_only = True
            
    
        # terminal_char_only = False
        if contains_non_dot_characters(clean_word) and terminal_char_only == False:
            #.....
            bigram_candidates = extract_characters_with_underscore(word)
                       #removed print

            # print('bigram_candidates: ', bigram_candidates)
            # if len(bigram_candidates)>0:
            #     terminal_char_only = False
                # bigram_candidates.remove('_')
                
    
            guess_data_frame = create_guess_data_frame(list(set(self.guessed_letters)))
            
            masked_bigram_frame = bigram_data_frame*guess_data_frame.to_numpy()
            all_bigram_count = masked_bigram_frame.sum().sum()
            prob_bigram_distr = masked_bigram_frame/all_bigram_count

            probability_dict = dict()
            for cand_ in bigram_candidates:
                idx_max_prob_a = prob_bigram_distr[cand_].argmax()
                p_a = prob_bigram_distr[cand_].iloc[idx_max_prob_a]
                probability_dict[cand_] = p_a

            # Get the key corresponding to the max value
            max_key = max(probability_dict, key=lambda k: probability_dict[k])
                       #removed print

            # print('Initial char of the bigram: ', max_key)  # Output: 'banana'
            idx_max_prob = prob_bigram_distr[max_key].argmax()
            
            guess_letter_a = prob_bigram_distr.columns[idx_max_prob]
                       #removed print

            # print('bigram model predicted guess word ' , guess_letter_a)    
            return guess_letter_a
            # else:
            #     print('Setting terminal_char_only to True')
            #     terminal_char_only = True
        # elif terminal_char_only == True or not contains_non_dot_characters(clean_word):
        else:
            # if terminal_char_only == True:
                           #removed print

                # print('In this loop because terminal char arrived')
            # find length of passed word
            terminal_char_only = False
            len_word = len(clean_word)
    
            
            # grab current dictionary of possible words from self object, initialize new possible words dictionary to empty
            current_dictionary = self.current_dictionary
            new_dictionary = []
            
            # iterate through all of the words in the old plausible dictionary
            for dict_word in current_dictionary:
                # continue if the word is not of the appropriate length
                if len(dict_word) != len_word:
                    continue
                    
                # if dictionary word is a possible match then add it to the current dictionary
                if re.match(clean_word,dict_word):
                    new_dictionary.append(dict_word)
                # new_dictionary.append(dict_word)
                       #removed print

            # print(new_dictionary[:3],len(new_dictionary))
            
            for wrong_guessed_letter in self.wrong_guess:
                new_dictionary = [word for word in new_dictionary if wrong_guessed_letter not in word]
           #removed print
            # print(new_dictionary[:3],len(new_dictionary))
            # overwrite old possible words dictionary with updated version
            # self.current_dictionary = new_dictionary
            
            
            # count occurrence of all characters in possible word matches
            full_dict_string = "".join(new_dictionary)
            
            c = collections.Counter(full_dict_string)
            sorted_letter_count = c.most_common()                   
            
            guess_letter = '!'
            
            # return most frequently occurring letter in all possible words that hasn't been guessed yet
            for letter,instance_count in sorted_letter_count:
                if letter not in self.guessed_letters:
                    guess_letter = letter
                    break
                
            # if no word matches in training dictionary, default back to ordering of full dictionary
            if guess_letter == '!':
                sorted_letter_count = self.full_dictionary_common_letter_sorted
                for letter,instance_count in sorted_letter_count:
                    if letter not in self.guessed_letters:
                        guess_letter = letter
                        break            
            
            return guess_letter

    ##########################################################
    # You'll likely not need to modify any of the code below #
    ##########################################################
    
    def build_dictionary(self, dictionary_file_location):
        text_file = open(dictionary_file_location,"r")
        full_dictionary = text_file.read().splitlines()
        text_file.close()
        return full_dictionary
                
    def start_game(self, practice=True, verbose=True):
        # reset guessed letters to empty set and current plausible dictionary to the full dictionary
        self.guessed_letters = []
        self.current_dictionary = self.full_dictionary
        self.wrong_guess = []                 
        response = self.request("/new_game", {"practice":practice})
        mistake_counter = 0
        max_allowed_mistakes = 6
        if response.get('status')=="approved":
            game_id = response.get('game_id')
            word = response.get('word')
            tries_remains = response.get('tries_remains')

            if verbose:
                print("Successfully start a new game! Game ID: {0}. # of tries remaining: {1}. Word: {2}.".format(game_id, tries_remains, word))
            while tries_remains>0:
                # get guessed letter from user code
                guess_letter = self.guess(word)
                    
                # append guessed letter to guessed letters field in hangman object
                self.guessed_letters.append(guess_letter)
                if verbose:
                    print("Guessing letter: {0}".format(guess_letter))
                    
                try:    
                    res = self.request("/guess_letter", {"request":"guess_letter", "game_id":game_id, "letter":guess_letter})
                except HangmanAPIError:
                    print('HangmanAPIError exception caught on request.')
                    continue
                except Exception as e:
                    print('Other exception caught on request.')
                    raise e
               
                if verbose:
                    print("Sever response: {0}".format(res))
                status = res.get('status')
                tries_remains = res.get('tries_remains')
                mistake_counter = max_allowed_mistakes - tries_remains
                # print(mistake_counter)
                if mistake_counter>0:
                    self.wrong_guess.append(guess_letter)
                    max_allowed_mistakes = max_allowed_mistakes - 1

                if status=="success":
                    if verbose:
                        print("Successfully finished game: {0}".format(game_id))
                    return True
                elif status=="failed":
                    reason = res.get('reason', '# of tries exceeded!')
                    if verbose:
                        print("Failed game: {0}. Because of: {1}".format(game_id, reason))
                    return False
                elif status=="ongoing":
                    word = res.get('word')
        else:
            if verbose:
                print("Failed to start a new game")
        return status=="success"
        
    def my_status(self):
        return self.request("/my_status", {})
    
    def request(
            self, path, args=None, post_args=None, method=None):
        if args is None:
            args = dict()
        if post_args is not None:
            method = "POST"

        # Add `access_token` to post_args or args if it has not already been
        # included.
        if self.access_token:
            # If post_args exists, we assume that args either does not exists
            # or it does not need `access_token`.
            if post_args and "access_token" not in post_args:
                post_args["access_token"] = self.access_token
            elif "access_token" not in args:
                args["access_token"] = self.access_token

        time.sleep(0.2)

        num_retry, time_sleep = 50, 2
        for it in range(num_retry):
            try:
                response = self.session.request(
                    method or "GET",
                    self.hangman_url + path,
                    timeout=self.timeout,
                    params=args,
                    data=post_args,
                    verify=False
                )
                break
            except requests.HTTPError as e:
                response = json.loads(e.read())
                raise HangmanAPIError(response)
            except requests.exceptions.SSLError as e:
                if it + 1 == num_retry:
                    raise
                time.sleep(time_sleep)

        headers = response.headers
        if 'json' in headers['content-type']:
            result = response.json()
        elif "access_token" in parse_qs(response.text):
            query_str = parse_qs(response.text)
            if "access_token" in query_str:
                result = {"access_token": query_str["access_token"][0]}
                if "expires" in query_str:
                    result["expires"] = query_str["expires"][0]
            else:
                raise HangmanAPIError(response.json())
        else:
            raise HangmanAPIError('Maintype was not text, or querystring')

        if result and isinstance(result, dict) and result.get("error"):
            raise HangmanAPIError(result)
        return result
    
class HangmanAPIError(Exception):
    def __init__(self, result):
        self.result = result
        self.code = None
        try:
            self.type = result["error_code"]
        except (KeyError, TypeError):
            self.type = ""

        try:
            self.message = result["error_description"]
        except (KeyError, TypeError):
            try:
                self.message = result["error"]["message"]
                self.code = result["error"].get("code")
                if not self.type:
                    self.type = result["error"].get("type", "")
            except (KeyError, TypeError):
                try:
                    self.message = result["error_msg"]
                except (KeyError, TypeError):
                    self.message = result

        Exception.__init__(self, self.message)

# API Usage Examples

## To start a new game:
1. Make sure you have implemented your own "guess" method.
2. Use the access_token that we sent you to create your HangmanAPI object. 
3. Start a game by calling "start_game" method.
4. If you wish to test your function without being recorded, set "practice" parameter to 1.
5. Note: You have a rate limit of 20 new games per minute. DO NOT start more than 20 new games within one minute.

In [238]:
api = HangmanAPI(access_token="8d066fa9d3c4785c59944618903abd", timeout=2000)

## Playing practice games:
You can use the command below to play up to 100,000 practice games.

In [239]:
api.start_game(practice=1,verbose=True)
[total_practice_runs,total_recorded_runs,total_recorded_successes,total_practice_successes] = api.my_status() # Get my game stats: (# of tries, # of wins)
practice_success_rate = total_practice_successes / total_practice_runs
print('run %d practice games out of an allotted 100,000. practice success rate so far = %.3f' % (total_practice_runs, practice_success_rate))


Successfully start a new game! Game ID: 4b0444c0b395. # of tries remaining: 6. Word: _ _ _ _ _ _ _ _ _ .
Guessing letter: e
Sever response: {'game_id': '4b0444c0b395', 'status': 'ongoing', 'tries_remains': 6, 'word': '_ _ _ _ e _ _ _ e '}
Guessing letter: r
Sever response: {'game_id': '4b0444c0b395', 'status': 'ongoing', 'tries_remains': 5, 'word': '_ _ _ _ e _ _ _ e '}
Guessing letter: s
Sever response: {'game_id': '4b0444c0b395', 'status': 'ongoing', 'tries_remains': 4, 'word': '_ _ _ _ e _ _ _ e '}
Guessing letter: n
Sever response: {'game_id': '4b0444c0b395', 'status': 'ongoing', 'tries_remains': 4, 'word': '_ _ _ _ e _ _ n e '}
Guessing letter: d
Sever response: {'game_id': '4b0444c0b395', 'status': 'ongoing', 'tries_remains': 3, 'word': '_ _ _ _ e _ _ n e '}
Guessing letter: l
Sever response: {'game_id': '4b0444c0b395', 'status': 'ongoing', 'tries_remains': 3, 'word': '_ _ _ l e _ _ n e '}
Guessing letter: t
Sever response: {'game_id': '4b0444c0b395', 'status': 'ongoing', 'tries_

In [242]:
for i in range(5000):
    print('Playing ', i, ' th game')
    # Uncomment the following line to execute your final runs. Do not do this until you are satisfied with your submission
    api.start_game(practice=1,verbose=True)
    [total_practice_runs,total_recorded_runs,total_recorded_successes,total_practice_successes] = api.my_status() # Get my game stats: (# of tries, # of wins)
    practice_success_rate = total_practice_successes / total_practice_runs
    print('run %d practice games out of an allotted 100,000. practice success rate so far = %.3f' % (total_practice_runs, practice_success_rate))

    # DO NOT REMOVE as otherwise the server may lock you out for too high frequency of requests
    time.sleep(0.5)

Playing  0  th game
Successfully start a new game! Game ID: 97ac050821a8. # of tries remaining: 6. Word: _ _ _ _ _ _ _ _ _ _ .
Guessing letter: e
Sever response: {'game_id': '97ac050821a8', 'status': 'ongoing', 'tries_remains': 6, 'word': '_ _ _ _ _ _ _ e _ _ '}
Guessing letter: r
Sever response: {'game_id': '97ac050821a8', 'status': 'ongoing', 'tries_remains': 6, 'word': '_ _ _ _ _ _ _ e r _ '}
Guessing letter: i
Sever response: {'game_id': '97ac050821a8', 'status': 'ongoing', 'tries_remains': 6, 'word': '_ _ _ i _ _ _ e r _ '}
Guessing letter: n
Sever response: {'game_id': '97ac050821a8', 'status': 'ongoing', 'tries_remains': 6, 'word': '_ _ _ i n _ _ e r _ '}
Guessing letter: a
Sever response: {'game_id': '97ac050821a8', 'status': 'ongoing', 'tries_remains': 5, 'word': '_ _ _ i n _ _ e r _ '}
Guessing letter: g
Sever response: {'game_id': '97ac050821a8', 'status': 'ongoing', 'tries_remains': 4, 'word': '_ _ _ i n _ _ e r _ '}
Guessing letter: o
Sever response: {'game_id': '97ac05082

KeyboardInterrupt: 

In [218]:
# extract_characters_with_underscore(word)

In [207]:
word = 'c _ e r n o _ i t _ '
guessed_letters_offline = ['e', 'r', 'i']
bigram_model(word, guessed_letters_offline)

bigram_candidates:  ['t', 'c', 'o']
Initial char of the bigram:  o
bigram model predicted guess word  n


In [143]:
api.guessed_letters

['e', 'a', 'i', 'n', 's', 'c', 'g', 't', 'o', 'r', 'h']

In [147]:
prob_bigram_distr['i']

a    0.007212
b    0.001653
c    0.012421
d    0.005067
e    0.005098
f    0.002155
g    0.002793
h    0.000168
i    0.000259
j    0.000065
k    0.000941
l    0.006529
m    0.003022
n    0.000000
o    0.007397
p    0.002531
q    0.000174
r    0.002979
s    0.012582
t    0.000000
u    0.000810
v    0.002895
w    0.000061
x    0.000315
y    0.000043
z    0.002751
Name: i, dtype: float64

In [145]:
prob_bigram_distr['i'].argmax()

18

In [110]:
ttt = extract_characters_with_underscore('_ _ _ _ _ _ _ _ _ _ _ _ _ e _ _ _ ')

In [111]:
ttt.remove('_')

In [112]:
ttt

['e']

In [ ]:
api.wrong_guess

## Playing recorded games:
Please finalize your code prior to running the cell below. Once this code executes once successfully your submission will be finalized. Our system will not allow you to rerun any additional games.

Please note that it is expected that after you successfully run this block of code that subsequent runs will result in the error message "Your account has been deactivated".

Once you've run this section of the code your submission is complete. Please send us your source code via email.

In [ ]:
for i in range(1000):
    print('Playing ', i, ' th game')
    # Uncomment the following line to execute your final runs. Do not do this until you are satisfied with your submission
    #api.start_game(practice=0,verbose=False)
    
    # DO NOT REMOVE as otherwise the server may lock you out for too high frequency of requests
    time.sleep(0.5)

## To check your game statistics
1. Simply use "my_status" method.
2. Returns your total number of games, and number of wins.

In [ ]:
[total_practice_runs,total_recorded_runs,total_recorded_successes,total_practice_successes] = api.my_status() # Get my game stats: (# of tries, # of wins)
success_rate = total_recorded_successes/total_recorded_runs
print('overall success rate = %.3f' % success_rate)

In [11]:
def build_dictionary(dictionary_file_location):
    text_file = open(dictionary_file_location,"r")
    full_dictionary = text_file.read().splitlines()
    text_file.close()
    return full_dictionary

In [13]:
word_list = build_dictionary('./words_250000_train.txt')

In [14]:
len(word_list)

227300

In [15]:
import string
import pandas as pd

def create_bigram_data_frame(word_list):
    # Step 1: Count bigrams for each character
    bigram_counts = {}
    
    for word in word_list:
        word = word.lower()  # Convert all words to lowercase for case-insensitive comparison
        word_length = len(word)
        
        for i in range(word_length - 1):
            bigram = word[i:i+2]
            
            # Count bigrams
            first_char = bigram[0]
            second_char = bigram[1]
            if first_char not in bigram_counts:
                bigram_counts[first_char] = {}
            if second_char in bigram_counts[first_char]:
                bigram_counts[first_char][second_char] += 1
            else:
                bigram_counts[first_char][second_char] = 1

    # Step 2: Create the data frame with all bigrams having count 0
    all_chars = string.ascii_lowercase
    df_data = {first_char: {second_char: bigram_counts.get(first_char, {}).get(second_char, 0) for second_char in all_chars}
               for first_char in all_chars}
    
    df = pd.DataFrame(df_data)

    return df

# Example usage:
# word_list = ['appetizingly', 'appraisingly', 'backbitingly']
bigram_data_frame = create_bigram_data_frame(word_list)

print(bigram_data_frame.T)


       a     b      c      d      e     f     g      h      i    j  ...     q  \
a    270  5416  13089   5429  10223  2623  4660   9559  11742  992  ...    20   
b   7258  1076     28    369   2171    90   173    269   2691    2  ...     1   
c  10476   221   1423    256   7706   197    66    147  20223   11  ...     4   
d   6110   250     68   1321  23098   159   117    126   8250    8  ...     3   
e   3350  5974   9023  13954   5426  3328  7326  11707   8301  735  ...     5   
f   1383    89     34    321   2340  2055   103    202   3508    3  ...     3   
g   4914    48     32    734   2617    46  1315     67   4548    3  ...     1   
h   1089   126  12023    383   1014    61  2377    109    274    5  ...     1   
i   4512  5052   6429  10976   2838  4404  4788   9035    421  267  ...    11   
j    211   148      1    175    265    20    21     15    106    6  ...     0   
k   2070    24   4537     43    573    20    31     60   1532    9  ...     1   
l  23550  7122   3169   1925

In [21]:
bigram_data_frame['a'].argmax()

13

In [34]:
print(bigram_data_frame['a'])

a      270
b     7258
c    10476
d     6110
e     3350
f     1383
g     4914
h     1089
i     4512
j      211
k     2070
l    23550
m     6969
n    25117
o      256
p     6038
q      204
r    19848
s    10554
t    23611
u     3471
v     2413
w     1345
x      751
y     1884
z      964
Name: a, dtype: int64


In [61]:
masked_bigram_frame = bigram_data_frame*guess_data_frame.to_numpy()

In [62]:
bigram_data_frame['a']

a      270
b     7258
c    10476
d     6110
e     3350
f     1383
g     4914
h     1089
i     4512
j      211
k     2070
l    23550
m     6969
n    25117
o      256
p     6038
q      204
r    19848
s    10554
t    23611
u     3471
v     2413
w     1345
x      751
y     1884
z      964
Name: a, dtype: int64

In [63]:
masked_bigram_frame['a']

a      270
b     7258
c    10476
d     6110
e     3350
f     1383
g     4914
h     1089
i     4512
j      211
k     2070
l    23550
m     6969
n        0
o      256
p     6038
q      204
r    19848
s    10554
t        0
u     3471
v     2413
w     1345
x      751
y     1884
z      964
Name: a, dtype: int64

In [64]:
all_bigram_count = masked_bigram_frame.sum().sum()

In [65]:
# prob_bigram_distr = bigram_data_frame/bigram_data_frame.sum(axis=0)
prob_bigram_distr = masked_bigram_frame/all_bigram_count

In [66]:
idx_max_prob = prob_bigram_distr['a'].argmax()

In [67]:
prob_bigram_distr['a'].iloc[idx_max_prob]

0.01446446471039132

In [68]:
prob_bigram_distr.columns[idx_max_prob]

'l'

In [137]:
import string
import pandas as pd

def create_guess_data_frame(guessed_letters):
    all_chars = string.ascii_lowercase
    data = {char: [0 if char in guessed_letters else 1 if char != guessed_letters else 0 for _ in range(len(all_chars))] for char in all_chars}
    df = pd.DataFrame(data, index=list(all_chars))
    return df.T

# Example usage:
guessed_letters = ['r', 'e']
guess_data_frame = create_guess_data_frame(guessed_letters)

print(guess_data_frame.to_numpy())


[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 1 1 1 

In [203]:
import re

def extract_characters_with_underscore(input_string):
    pattern = r'\b(\w)(?=_*)'
    characters = re.findall(pattern, input_string)
    return list(set(characters))

# Example usage:
test_string1 = '_ _ _ _ _ _ _ _ _ _ e'
result1 = extract_characters_with_underscore(test_string1)
print(result1)  # Output: ['i', 'a']

test_string2 = 'c _ e r n o _ i t _ '

result2 = extract_characters_with_underscore(test_string2)
print(result2)  # Output: ['i', 'a']


['e', '_']
['n', '_', 'e', 'c', 'i', 't', 'r', 'o']


In [206]:
def extract_characters_with_underscore(input_string):
    bigrams = input_string.split()
    char_underscore_bigrams = []

    for i in range(len(bigrams) - 1):
        if bigrams[i + 1] == '_':
            char_underscore_bigrams.append(bigrams[i])
    char_underscore_bigrams = list(set(char_underscore_bigrams))
    if '_' in char_underscore_bigrams:
        char_underscore_bigrams.remove('_')
    return char_underscore_bigrams

# Example usage:
input_string = 'n i _ j _ _ i _'
result = extract_characters_with_underscore(test_string2)
print(result)  # Output: ['i', 'j']


['t', 'c', 'o']


In [94]:
result1.remove('_')

In [95]:
result1

['i', 'a']

In [148]:
guess_data_frame = create_guess_data_frame(list(set(['i'])))


In [149]:
guess_data_frame

a  b  c  d  e  f  g  h  i  j  ...  q  r  s  t  u  v  w  x  y  z
a  1  1  1  1  1  1  1  1  1  1  ...  1  1  1  1  1  1  1  1  1  1
b  1  1  1  1  1  1  1  1  1  1  ...  1  1  1  1  1  1  1  1  1  1
c  1  1  1  1  1  1  1  1  1  1  ...  1  1  1  1  1  1  1  1  1  1
d  1  1  1  1  1  1  1  1  1  1  ...  1  1  1  1  1  1  1  1  1  1
e  1  1  1  1  1  1  1  1  1  1  ...  1  1  1  1  1  1  1  1  1  1
f  1  1  1  1  1  1  1  1  1  1  ...  1  1  1  1  1  1  1  1  1  1
g  1  1  1  1  1  1  1  1  1  1  ...  1  1  1  1  1  1  1  1  1  1
h  1  1  1  1  1  1  1  1  1  1  ...  1  1  1  1  1  1  1  1  1  1
i  0  0  0  0  0  0  0  0  0  0  ...  0  0  0  0  0  0  0  0  0  0
j  1  1  1  1  1  1  1  1  1  1  ...  1  1  1  1  1  1  1  1  1  1
k  1  1  1  1  1  1  1  1  1  1  ...  1  1  1  1  1  1  1  1  1  1
l  1  1  1  1  1  1  1  1  1  1  ...  1  1  1  1  1  1  1  1  1  1
m  1  1  1  1  1  1  1  1  1  1  ...  1  1  1  1  1  1  1  1  1  1
n  1  1  1  1  1  1  1  1  1  1  ...  1  1  1  1  1  1  1  1  1  1
o  1  1  1  1  1  1  1  1  1  1  ...  1  1  1  1  1  1  1  1  1  1
p  1  1  1  1  1  1  1  1  1  1  ...  1  1  1  1  1  1  1  1  1  1
q  1  1  1  1  1  1  1  1  1  1  ...  1  1  1  1  1  1  1  1  1  1
r  1  1  1  1  1  1  1  1  1  1  ...  1  1  1  1  1  1  1  1  1  1
s  1  1  1  1  1  1  1  1  1  1  ...  1  1  1  1  1  1  1  1  1  1
t  1  1  1  1  1  1  1  1  1  1  ...  1  1  1  1  1  1  1  1  1  1
u  1  1  1  1  1  1  1  1  1  1  ...  1  1  1  1  1  1  1  1  1  1
v  1  1  1  1  1  1  1  1  1  1  ...  1  1  1  1  1  1  1  1  1  1
w  1  1  1  1  1  1  1  1  1  1  ...  1  1  1  1  1  1  1  1  1  1
x  1  1  1  1  1  1  1  1  1  1  ...  1  1  1  1  1  1  1  1  1  1
y  1  1  1  1  1  1  1  1  1  1  ...  1  1  1  1  1  1  1  1  1  1
z  1  1  1  1  1  1  1  1  1  1  ...  1  1  1  1  1  1  1  1  1  1

[26 rows x 26 columns]

In [150]:
masked_bigram_frame = bigram_data_frame*guess_data_frame.to_numpy()


In [151]:
masked_bigram_frame

a     b      c      d      e     f     g      h      i    j  ...     q  \
a    270  5416  13089   5429  10223  2623  4660   9559  11742  992  ...    20   
b   7258  1076     28    369   2171    90   173    269   2691    2  ...     1   
c  10476   221   1423    256   7706   197    66    147  20223   11  ...     4   
d   6110   250     68   1321  23098   159   117    126   8250    8  ...     3   
e   3350  5974   9023  13954   5426  3328  7326  11707   8301  735  ...     5   
f   1383    89     34    321   2340  2055   103    202   3508    3  ...     3   
g   4914    48     32    734   2617    46  1315     67   4548    3  ...     1   
h   1089   126  12023    383   1014    61  2377    109    274    5  ...     1   
i      0     0      0      0      0     0     0      0      0    0  ...     0   
j    211   148      1    175    265    20    21     15    106    6  ...     0   
k   2070    24   4537     43    573    20    31     60   1532    9  ...     1   
l  23550  7122   3169   1925  14123  2487  3363   1069  10630    4  ...     4   
m   6969   151     75    448   7347    89   476    597   4921    4  ...     3   
n  25117   110    151    944  23199    40  1589    627  37762   13  ...     3   
o    256  4514  14169   5147   3025  3560  3049   8845  12043  756  ...     3   
p   6038   122     51    190   5034   116    81    140   4121    3  ...     1   
q    204     5    113      8    526     6     2     13    284    0  ...     4   
r  19848  4084   4845   3164  39200  2019  4455   2505   4851    7  ...     4   
s  10554   897    607   1733  27128   349  1013    600  20485   10  ...    10   
t  23611   280   5616    213  10786   926   215   1862  14248    2  ...     5   
u   3471  3014   4345   2147   2600  2299  2361   1953   1318  901  ...  3857   
v   2413    79     16    270   2369    18    18     38   4713    1  ...     2   
w   1345    54     22    387   1677    68   176    296     99    2  ...     4   
x    751     3      2      4   2888     3     1      1    513    0  ...     0   
y   1884   480   1932   1164   1592   504  1106   4286     70    8  ...     0   
z    964     6     37     37    315     3    10     10   4479    0  ...     0   

       r      s      t      u      v     w    x     y     z  
a  20481   5684  12414   2908   3060  3292  585  1364  1421  
b   1913    523    437   3074      3   191   35   402    23  
c   3388   5533   1246   2667     11   104  350  1320    11  
d   3773    235    171   2235     12   181   15   863    13  
e  24800  13813  26219   2259  10593  3228  638  1380  3531  
f    969    333    528    619      4   114   37   267     5  
g   2254    187    213   1661      9    42    9   526     9  
h   1206   7431  10336     74      4  1065  118   185    23  
i      0      0      0      0      0     0    0     0     0  
j    111     47     50     65      1     5    3    15     1  
k   1282   1291     67    360     16   113    2    72    19  
l   1999   2306   2137   8026     34   387   60  2197   145  
m   3945   4173    587   4969     15   116   27  1353    23  
n   2930   1509    474  15154     18   997   11  1449    16  
o  18733   5481  12632    586   1571  2508  408   989  1037  
p   2021   5151    308   2942      7    73  540  2029    12  
q     93    591     16     29      0     1    6     7     2  
r   3609    210  11607   8776     86   541   16  1146    14  
s   6776  12161   3462  11339     58   461   71  2150    23  
t   5494  20183   4181   5487     13   134  685  1301    17  
u   3813   5905   4243     43    244    84  158   152   107  
v   1117    317     96    268     28    12    5    84     7  
w    581    982   1188     27      3    77   25   243    17  
x     10      5      5    260      1     0    7   108     0  
y   4394   1699   4137     97    127   143  405    24   258  
z     98     35    318    188      3    14    1   121   342  

[26 rows x 26 columns]

In [152]:
all_bigram_count = masked_bigram_frame.sum().sum()
prob_bigram_distr = masked_bigram_frame/all_bigram_count


In [153]:
prob_bigram_distr

a         b             c         d         e         f  \
a  0.000157  0.003149  7.609207e-03  0.003156  0.005943  0.001525   
b  0.004219  0.000626  1.627762e-05  0.000215  0.001262  0.000052   
c  0.006090  0.000128  8.272520e-04  0.000149  0.004480  0.000115   
d  0.003552  0.000145  3.953137e-05  0.000768  0.013428  0.000092   
e  0.001948  0.003473  5.245464e-03  0.008112  0.003154  0.001935   
f  0.000804  0.000052  1.976568e-05  0.000187  0.001360  0.001195   
g  0.002857  0.000028  1.860300e-05  0.000427  0.001521  0.000027   
h  0.000633  0.000073  6.989495e-03  0.000223  0.000589  0.000035   
i  0.000000  0.000000  0.000000e+00  0.000000  0.000000  0.000000   
j  0.000123  0.000086  5.813436e-07  0.000102  0.000154  0.000012   
k  0.001203  0.000014  2.637556e-03  0.000025  0.000333  0.000012   
l  0.013691  0.004140  1.842278e-03  0.001119  0.008210  0.001446   
m  0.004051  0.000088  4.360077e-05  0.000260  0.004271  0.000052   
n  0.014602  0.000064  8.778289e-05  0.000549  0.013487  0.000023   
o  0.000149  0.002624  8.237058e-03  0.002992  0.001759  0.002070   
p  0.003510  0.000071  2.964853e-05  0.000110  0.002926  0.000067   
q  0.000119  0.000003  6.569183e-05  0.000005  0.000306  0.000003   
r  0.011539  0.002374  2.816610e-03  0.001839  0.022789  0.001174   
s  0.006136  0.000521  3.528756e-04  0.001007  0.015771  0.000203   
t  0.013726  0.000163  3.264826e-03  0.000124  0.006270  0.000538   
u  0.002018  0.001752  2.525938e-03  0.001248  0.001511  0.001337   
v  0.001403  0.000046  9.301498e-06  0.000157  0.001377  0.000010   
w  0.000782  0.000031  1.278956e-05  0.000225  0.000975  0.000040   
x  0.000437  0.000002  1.162687e-06  0.000002  0.001679  0.000002   
y  0.001095  0.000279  1.123156e-03  0.000677  0.000925  0.000293   
z  0.000560  0.000003  2.150971e-05  0.000022  0.000183  0.000002   

              g             h         i             j  ...             q  \
a  2.709061e-03  5.557064e-03  0.006826  5.766929e-04  ...  1.162687e-05   
b  1.005724e-04  1.563814e-04  0.001564  1.162687e-06  ...  5.813436e-07   
c  3.836868e-05  8.545751e-05  0.011757  6.394780e-06  ...  2.325375e-06   
d  6.801721e-05  7.324930e-05  0.004796  4.650749e-06  ...  1.744031e-06   
e  4.258923e-03  6.805790e-03  0.004826  4.272876e-04  ...  2.906718e-06   
f  5.987839e-05  1.174314e-04  0.002039  1.744031e-06  ...  1.744031e-06   
g  7.644669e-04  3.895002e-05  0.002644  1.744031e-06  ...  5.813436e-07   
h  1.381854e-03  6.336646e-05  0.000159  2.906718e-06  ...  5.813436e-07   
i  0.000000e+00  0.000000e+00  0.000000  0.000000e+00  ...  0.000000e+00   
j  1.220822e-05  8.720155e-06  0.000062  3.488062e-06  ...  0.000000e+00   
k  1.802165e-05  3.488062e-05  0.000891  5.232093e-06  ...  5.813436e-07   
l  1.955059e-03  6.214563e-04  0.006180  2.325375e-06  ...  2.325375e-06   
m  2.767196e-04  3.470622e-04  0.002861  2.325375e-06  ...  1.744031e-06   
n  9.237550e-04  3.645025e-04  0.021953  7.557467e-06  ...  1.744031e-06   
o  1.772517e-03  5.141984e-03  0.007001  4.394958e-04  ...  1.744031e-06   
p  4.708883e-05  8.138811e-05  0.002396  1.744031e-06  ...  5.813436e-07   
q  1.162687e-06  7.557467e-06  0.000165  0.000000e+00  ...  2.325375e-06   
r  2.589886e-03  1.456266e-03  0.002820  4.069405e-06  ...  2.325375e-06   
s  5.889011e-04  3.488062e-04  0.011909  5.813436e-06  ...  5.813436e-06   
t  1.249889e-04  1.082462e-03  0.008283  1.162687e-06  ...  2.906718e-06   
u  1.372552e-03  1.135364e-03  0.000766  5.237906e-04  ...  2.242242e-03   
v  1.046419e-05  2.209106e-05  0.002740  5.813436e-07  ...  1.162687e-06   
w  1.023165e-04  1.720777e-04  0.000058  1.162687e-06  ...  2.325375e-06   
x  5.813436e-07  5.813436e-07  0.000298  0.000000e+00  ...  0.000000e+00   
y  6.429661e-04  2.491639e-03  0.000041  4.650749e-06  ...  0.000000e+00   
z  5.813436e-06  5.813436e-06  0.002604  0.000000e+00  ...  0.000000e+00   

          r         s         t         u             v             w  \
a  0.011906  0.00330

In [154]:

probability_dict = dict()
for cand_ in ['i']:
    idx_max_prob_a = prob_bigram_distr[cand_].argmax()
    p_a = prob_bigram_distr[cand_].iloc[idx_max_prob_a]
    probability_dict[cand_] = p_a


In [157]:
idx_max_prob_a

13

In [156]:
prob_bigram_distr['i']

a    0.006826
b    0.001564
c    0.011757
d    0.004796
e    0.004826
f    0.002039
g    0.002644
h    0.000159
i    0.000000
j    0.000062
k    0.000891
l    0.006180
m    0.002861
n    0.021953
o    0.007001
p    0.002396
q    0.000165
r    0.002820
s    0.011909
t    0.008283
u    0.000766
v    0.002740
w    0.000058
x    0.000298
y    0.000041
z    0.002604
Name: i, dtype: float64

In [155]:
probability_dict

{'i': 0.0219526983936894}

In [187]:
word = 'n i _ _ _ _ i _ '
guessed_letters_offline = ['i', 'n']
bigram_model(word, guessed_letters_offline)

['i']
i
bigram model predicted guess word  s


In [176]:
bigram_candidates

['i', 'n']

In [191]:
def bigram_model(word, guessed_letters_offline):
    bigram_candidates = extract_characters_with_underscore(word)
    print('bigram_candidates: ', bigram_candidates)
    if len(bigram_candidates)>0:
        terminal_char_only = False
        # bigram_candidates.remove('_')
        

        guess_data_frame = create_guess_data_frame(list(set(guessed_letters_offline)))
        
        masked_bigram_frame = bigram_data_frame*guess_data_frame.to_numpy()
        all_bigram_count = masked_bigram_frame.sum().sum()
        prob_bigram_distr = masked_bigram_frame/all_bigram_count

        probability_dict = dict()
        for cand_ in bigram_candidates:
            idx_max_prob_a = prob_bigram_distr[cand_].argmax()
            p_a = prob_bigram_distr[cand_].iloc[idx_max_prob_a]
            probability_dict[cand_] = p_a

        # Get the key corresponding to the max value
        max_key = max(probability_dict, key=lambda k: probability_dict[k])
        
        print('Initial char of the bigram: ', max_key)  # Output: 'banana'
        idx_max_prob = prob_bigram_distr[max_key].argmax()
        
        guess_letter_a = prob_bigram_distr.columns[idx_max_prob]
        print('bigram model predicted guess word ' , guess_letter_a)    
                
    

['i']
i
bigram model predicted guess word  s


In [ ]:


# Get the key corresponding to the max value
max_key = max(probability_dict, key=lambda k: probability_dict[k])

print(max_key)  # Output: 'banana'
idx_max_prob = prob_bigram_distr[max_key].argmax()

guess_letter_a = prob_bigram_distr.columns[idx_max_prob]
print('bigram model predicted guess word ' , guess_letter_a)    
return guess_letter_a